### ISSUE TITLE
LoadLibrary加载动态库失败

### ISSUE THREAD

**Issue by XC-Hsm** [Sc-Softs/CornerstoneSDK#4]
在汇报漏洞前请确保已经仔细阅读了SDK文档并确保问题能够重现。

**发生了什么？**
用c++sdk写的插件载入失败，提示插件名——LoadLibraryA加载失败

**怎样重现？**
无法重现，目前测试多台设备，同样的插件，只有我的设备出现了问题，我的设备中易语言编写的插件没有问题
而且我后来并未对官方sdk作更改，直接编译后也出现了问题。

想联系大佬帮我康康

**Comment by XC-Hsm** [comment]
> 在汇报漏洞前请确保已经仔细阅读了SDK文档并确保问题能够重现。
> 
> **发生了什么？**
> 用c++sdk写的插件载入失败，提示插件名——LoadLibraryA加载失败
> 
> **怎样重现？**
> 无法重现，目前测试多台设备，同样的插件，只有我的设备出现了问题，我的设备中易语言编写的插件没有问题
> 而且我后来并未对官方sdk作更改，直接编译后也出现了问题。
> 
> 想联系大佬帮我康康
我的QQ：1657673426

**Comment by dynilath** [comment]
我猜可能是需要装个[visual c++ runtime](https://www.microsoft.com/zh-CN/download/details.aspx?id=48145)

**Comment by XC-Hsm** [comment]
> 我猜可能是需要装个[visual c++ runtime](https://www.microsoft.com/zh-CN/download/details.aspx?id=48145)

已经解决了 谢谢
