### ISSUE TITLE
访问无效内存

### ISSUE THREAD

**Issue by orion-tan** [Sc-Softs/CornerstoneSDK#5]
在汇报漏洞前请确保已经仔细阅读了SDK文档并确保问题能够重现。

**发生了什么？**
请清晰简练地描述出现的问题。
处理群消息事件时，群主可以正常触发关键词，其他群成员触发关键词会引起插件错误，提示访问无效内存

**怎样重现？**
请给出重现需要的步骤：
1. 打开XXX
2. 调用XXX
3. 构建XXX
4. 出现问题

**正常情况下应该会怎样？**
请清晰简练地描述正常情况下应该出现的现象。
正常情况应该所有人都可以触发

**使用了什么开发环境？**
 - Windows 版本：[ Windows 10 专业版]
 - Windows 版本号：[例如 1909]
 - [ ] 使用 VS + MSVC

如果有截图或其他有关事项请注明。

**Comment by dynilath** [comment]
这种非常像是业务代码写错了，建议先附加上去，断点调试一下。

**Comment by NKID00** [comment]
请给出必要的出错源码和栈帧谢谢。

（长时间不给有用信息就关 Issue 吧）
